### ISSUE TITLE
Crawling backlinks from auth pages not working

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#23]
ACHE can use an external API (such as lsapi.seomoz.com) to crawl backlinks from authority pages. But, currently, this feature is not working. The code is not updated and the seomoz API returns an HTTP 401 error.

To reproduce the error, following options should be configured:

in file `link_storage.cfg` change `SAVE_BACKLINKS` to true:

    SAVE_BACKLINKS TRUE

and the key `BACKLINK_CONFIG` should be changed to an absolute path for the file `backlink.cfg`:

    BACKLINK_CONFIG  /path/to/config/sample_config/link_storage/backlink.cfg

in file `target_storage.cfg`:

     BIPARTITE TRUE

Follows the stacktrace:

```
java.io.IOException: Server returned HTTP response code: 401 for URL: http://lsapi.seomoz.com/linkscape/links/www.businessinsider.com%2Fnew-york-city-ebola-2014-10?AccessID=member-2e52b09aae&Expires=1365280453&Signature=WFcSAnhBG62xmt2f57bGrqCtiOM%3D&Filter=external&Scope=page_to_page&Limit=50&Sort=page_authority&SourceCols=4&TargetCols=4
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at focusedCrawler.link.classifier.builder.BacklinkSurfer.downloadPage(BacklinkSurfer.java:248)
        at focusedCrawler.link.classifier.builder.BacklinkSurfer.downloadBacklinks(BacklinkSurfer.java:137)
        at focusedCrawler.link.classifier.builder.BacklinkSurfer.getLNBacklinks(BacklinkSurfer.java:172)
        at focusedCrawler.link.BipartiteGraphManager.insertBacklinks(BipartiteGraphManager.java:156)
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:168)
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:118)
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:391)
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284)
Generic Exception

[2015-07-24 12:28:16,413] INFO [crawler_group_2_0] (LinkStorage.java:201) - An Exception occurred.
java.lang.NullPointerException: null
        at focusedCrawler.link.classifier.builder.BacklinkSurfer.getLNBacklinks(BacklinkSurfer.java:173) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.link.BipartiteGraphManager.insertBacklinks(BipartiteGraphManager.java:156) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:168) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:118) [ache-0.3.1.jar:0.3.1]
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:391) [ache-0.3.1.jar:0.3.1]
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284) [ache-0.3.1.jar:0.3.1]
[2015-07-24 12:28:16,414]ERROR [crawler_group_2_0] (CrawlerImpl.java:397) - Problem while sending page to storage.
focusedCrawler.util.storage.StorageException: null
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:202) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:118) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:391) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284) [ache-0.3.1.jar:0.3.1]
[2015-07-24 12:28:16,415]ERROR [crawler_group_2_0] (Crawler.java:294) - crawler_group_2_0:null
focusedCrawler.crawler.CrawlerException: crawler_group_2_0:null
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:398) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284) ~[ache-0.3.1.jar:0.3.1]
java.lang.NullPointerException
        at focusedCrawler.link.classifier.builder.BacklinkSurfer.getLNBacklinks(BacklinkSurfer.java:173)
        at focusedCrawler.link.BipartiteGraphManager.insertBacklinks(BipartiteGraphManager.java:156)
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:168)
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:118)
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:391)
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284)
--
focusedCrawler.util.storage.StorageException
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:202)
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:118)
        at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:391)
        at focusedCrawler.crawler.Crawler.run(Crawler.java:284)

```

**Comment by rajatIIT** [comment]
Implemented a draft here which is able to download the backlinks :
https://github.com/rajatIIT/ache/commit/b5c9a911f0e699335d4686b8f15f4cb9f888ec77

**Comment by aecio** [comment]
Hi @rajatIIT, could you please add a config entry for the API user credentials, and then submit a pull request?

**Comment by rajatIIT** [comment]
Sure ! I did it here :
https://github.com/ViDA-NYU/ache/pull/30
