### ISSUE TITLE
TargetStorage fails to store pages because of too long file name

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#31]
TargetCBORRepository and TargetFileRepository eventualy fail to store pages because the file name is too long. A shorter name scheme should be used to avoid this errors. Example:

```
[2015-09-17 19:36:23,046]ERROR [dispatcher-22] (TargetCBORRepository.java:63) - Failed to store object in repository.
java.io.FileNotFoundException: ./data/data_target/www.trust.org/http%3A%2F%2Fwww.trust.org%2Fspotlight%2FEbola%2F%3Futm_medium%3Demail%26utm_campaign%3DAlertNet%2520Expresso%252028%2520Jan%25202015%26utm_content%3DAlertNet%2520Expresso%252028%2520Jan%25202015%2520CID_f5d471ee9a77c8bdd3ade118bd02acbe%26utm_source%3DCampaign%2520Monitor%26utm_term%3DEbola%2520outbreak%2520in%2520West%2520Africa (File name too long)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_60]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_60]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_60]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_60]
        at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1072) ~[jackson-core-2.5.4.jar:2.5.4]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2730) ~[jackson-databind-2.5.4.jar:2.5.4]
        at focusedCrawler.target.TargetCBORRepository.insert(TargetCBORRepository.java:60) ~[ache-0.3.1.jar:0.3.1]
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:91) [ache-0.3.1.jar:0.3.1]
        at [...]
```

**Comment by aecio** [comment]
Added a new option for data format FILESYSTEM_* that hashes the names of files to avoid this error in commit 58d6209c7d29b1c9c89194d951f7f37a0a08409b.
