### ISSUE TITLE
OutOfMemoryError problems during large crawls

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#62]
ACHE is stopping due to different types of `OutOfMemoryError`s being thrown during large crawls.

Examples:
```
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:201)
        at java.lang.String.toLowerCase(String.java:2635)
        at java.lang.String.toLowerCase(String.java:2658)
        at focusedCrawler.util.parser.PaginaURL.separadorTextoCodigo(PaginaURL.java:410)
        at focusedCrawler.util.parser.PaginaURL.<init>(PaginaURL.java:128)
        at focusedCrawler.util.parser.PaginaURL.<init>(PaginaURL.java:110)
        at focusedCrawler.util.vsm.VSMVector.<init>(VSMVector.java:167)
        at focusedCrawler.target.classifier.WekaTargetClassifier.getValues(WekaTargetClassifier.java:104)
        at focusedCrawler.target.classifier.WekaTargetClassifier.distributionForInstance(WekaTargetClassifier.java:90)
        at focusedCrawler.target.classifier.WekaTargetClassifier.classify(WekaTargetClassifier.java:74)
        at focusedCrawler.target.classifier.KeepLinkRelevanceTargetClassifier.classify(KeepLinkRelevanceTargetClassifier.java:22)
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:80)
        at focusedCrawler.crawler.async.FetchedResultHandler.processData(FetchedResultHandler.java:55)
        at focusedCrawler.crawler.async.FetchedResultHandler.completed(FetchedResultHandler.java:29)
        at focusedCrawler.crawler.async.HttpDownloader$FetchFinishedHandler.doHandle(HttpDownloader.java:330)
        at focusedCrawler.crawler.async.HttpDownloader$FetchFinishedHandler.run(HttpDownloader.java:313)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.substring(String.java:1957)
        at java.lang.String.split(String.java:2341)
        at java.lang.String.split(String.java:2410)
        at focusedCrawler.link.BipartiteGraphRepository.getLNs(BipartiteGraphRepository.java:104)
        at focusedCrawler.link.OnlineLearning.forwardClassifier(OnlineLearning.java:233)
        at focusedCrawler.link.OnlineLearning.execute(OnlineLearning.java:64)
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:183)
        at focusedCrawler.link.LinkStorage.insert(LinkStorage.java:124)
        at focusedCrawler.target.TargetStorage.insert(TargetStorage.java:98)
        at focusedCrawler.crawler.async.FetchedResultHandler.processData(FetchedResultHandler.java:55)
        at focusedCrawler.crawler.async.FetchedResultHandler.completed(FetchedResultHandler.java:29)
        at focusedCrawler.crawler.async.HttpDownloader$FetchFinishedHandler.doHandle(HttpDownloader.java:330)
        at focusedCrawler.crawler.async.HttpDownloader$FetchFinishedHandler.run(HttpDownloader.java:313)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$URLSerializer.read(DefaultSerializers.java:869)
        at com.esotericsoftware.kryo.serializers.DefaultSerializers$URLSerializer.read(DefaultSerializers.java:859)
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
        at focusedCrawler.util.persistence.rocksdb.RocksDBHashtable.unserializeObject(RocksDBHashtable.java:79)
        at focusedCrawler.util.persistence.rocksdb.RocksDBHashtable.access$100(RocksDBHashtable.java:21)
        at focusedCrawler.util.persistence.rocksdb.RocksDBHashtable$RocksDBIterator.next(RocksDBHashtable.java:172)
        at focusedCrawler.util.persistence.rocksdb.RocksDBHashtable$RocksDBIterator.next(RocksDBHashtable.java:125)
        at focusedCrawler.link.frontier.FrontierManager.loadQueue(FrontierManager.java:138)
        at focusedCrawler.link.frontier.FrontierManager.nextURL(FrontierManager.java:231)
        at focusedCrawler.link.LinkStorage.select(LinkStorage.java:213)
        at focusedCrawler.crawler.async.AsyncCrawler.run(AsyncCrawler.java:60)
        at focusedCrawler.Main.startCrawl(Main.java:310)
        at focusedCrawler.Main.main(Main.java:113)

```

**Comment by aecio** [comment]
Duplicate of issue #63 .
